Web/Controllers/PlayersController.cs
using E_SportManager.Data;
using E_SportManager.Models.Players;
using E_SportManager.Service.Data.Players;
using E_SportManager.Service.Providers.Pagination;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static E_SportManager.Common.ErrorMessages.Player;
using static E_SportManager.Common.GlobalConstants;
using static E_SportManager.Common.GlobalConstants.Player;

namespace E_SportManager.Controllers
{
    [Authorize]
    public class PlayersController : Controller
    {
        private readonly ESportDbContext data;
        private readonly IPlayerService playerService;

        public PlayersController(ESportDbContext data, IPlayerService playerService)
        {
            this.data = data;
            this.playerService = playerService;
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(AddPlayerFormModel input)
        {
            var isExisting = await playerService.IsExistingAsync(input.Name);

            if (!ModelState.IsValid)
            {
                return View();
            }

            if (isExisting)
            {
                ModelState.AddModelError(nameof(input.Name), PlayerExistingErrorMessage);
                return View(input);
            }


            var playerId = await playerService.CreatePlayerAsync(
                input.Name,
                input.ImageUrl,
                input.YearsOfExperience,
                input.Role,
                input.Division,
                input.Description,
                User.Id());


            TempData[GlobalMessageKey] = "Player was successfully created and is awaiting for approval!";

            return RedirectToAction(nameof(Details), new { id = playerId });
        }

        [AllowAnonymous]
        public async Task<IActionResult> All(AllPlayersQueryModel query, int page = 1)
        {
            var count = await playerService.GetTotalPlayersCountAsync();
            var skip = (page - 1) * PlayersPerPage;

            var players = await playerService.GetAllPlayersAsync<PlayerServiceModel>(skip);

            query.Players = players;
            query.Pagination = PaginationProvider.PaginationHelper(page, count, PlayersPerPage);

            return View(query);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var player = await playerService.GetByIdAsync<EditPlayerFormModel>(id);

            if (player == null)
            {
                return NotFound();
            }

            if (!User.IsAdministrator() || player.AuthorId != User.Id())
            {
                return Unauthorized();
            }

            return View(player);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditPlayerFormModel input)
        {
            if (!ModelState.IsValid)
            {
                return View(input);
            }

            var playerAuthorId = await playerService.GetPlayerAuthorIdAsync(input.Id);

            if (!User.IsAdministrator() || playerAuthorId != User.Id())
            {
                return Unauthorized();
            }

            var isExisting = await playerService.IsExistingAsync(input.Name, input.Id);

            if (isExisting)
            {
                ModelState.AddModelError(nameof(input.Name), PlayerExistingErrorMessage);
                return View(input);
            }


            await playerService.EditPlayerAsync(
                input.Id,
                input.Name,
                input.ImageUrl,
                input.YearsOfExperience,
                input.Role,
                input.Division,
                input.Description);

            TempData[GlobalMessageKey] = "Player was successfully edited and awaiting for approval!";

            return RedirectToAction(nameof(Details), new { id = input.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var player = await playerService.GetByIdAsync(id);

            if (player == null)
            {
                return NotFound();
            }

            if (!User.IsAdministrator() || player.AuthorId != User.Id())
            {
                return Unauthorized();
            }

            await playerService.DeletePlayerAsync(id);

            TempData[GlobalMessageKey] = "Player was successfully deleted!";


            return RedirectToAction(nameof(All));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var player = await playerService.GetByIdAsync<PlayerDetailsViewModel>(id);

            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }
    }
}

Web/Controllers/TeamsController.cs
using E_SportManager.Data;
using E_SportManager.Data.enums;
using E_SportManager.Models.Teams;
using E_SportManager.Service.Data.Teams;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static E_SportManager.Common.GlobalConstants;
using static E_SportManager.Common.GlobalConstants.Team;
using static E_SportManager.Common.ErrorMessages.Team;
using E_SportManager.Service.Providers.Pagination;

namespace E_SportManager.Controllers
{
    [Authorize]
    public class TeamsController : Controller
    {
        private readonly ESportDbContext data;
        private readonly ITeamService teamService;

        public TeamsController(ESportDbContext data, ITeamService teamService)
        {
            this.data = data;
            this.teamService = teamService;
        }

        public async Task<IActionResult> Create() => View(new AddTeamFormModel()
        {
            MidLaners = await teamService.GetRoleAsync(Role.Mid),
            BottomLaners = await teamService.GetRoleAsync(Role.Bottom),
            SupportLaners = await teamService.GetRoleAsync(Role.Support),
            JungleLaners = await teamService.GetRoleAsync(Role.Jungle),
            TopLaners = await teamService.GetRoleAsync(Role.Top)
        });


        [HttpPost]
        public async Task<IActionResult> Create(AddTeamFormModel input)
        {
            if (!ModelState.IsValid)
            {
                input.MidLaners = await teamService.GetRoleAsync(Role.Mid);
                input.BottomLaners = await teamService.GetRoleAsync(Role.Bottom);
                input.SupportLaners = await teamService.GetRoleAsync(Role.Support);
                input.JungleLaners = await teamService.GetRoleAsync(Role.Jungle);
                input.TopLaners = await teamService.GetRoleAsync(Role.Top);

                return View(input);
            }

            var isExisting = await teamService.IsExistingAsync(input.Title);

            if (isExisting)
            {
                ModelState.AddModelError(nameof(input.Title), TeamExistingErrorMessage);

                input.MidLaners = await teamService.GetRoleAsync(Role.Mid);
                input.BottomLaners = await teamService.GetRoleAsync(Role.Bottom);
                input.SupportLaners = await teamService.GetRoleAsync(Role.Support);
                input.JungleLaners = await teamService.GetRoleAsync(Role.Jungle);
                input.TopLaners = await teamService.GetRoleAsync(Role.Top);

                return View(input);
            }

            await teamService.CreateTeamAsync(
                input.Title,
                input.ImageUrl,
                input.MidLaner,
                input.TopLaner,
                input.JungleLaner,
                input.BottomLaner,
                input.SupportLaner,
                User.Id());

            TempData[GlobalMessageKey] = "Team was successfully created!";

            return RedirectToAction(nameof(All));
        }

        [AllowAnonymous]
        public async Task<IActionResult> All(AllTeamsQueryModel query, int page = 1)
        {
            var count = await teamService.GetTotalTeamsCountAsync();
            var skip = (page - 1) * TeamsPerPage;

            var teams = await teamService.GetAllTeamsAsync<TeamServiceModel>(skip);

            query.Teams = teams;
            query.Pagination = PaginationProvider.PaginationHelper(page, count, TeamsPerPage);

            return View(query);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var team = await teamService.GetByIdAsync(id);

            if (team == null)
            {
                return NotFound();
            }


            if (!User.IsAdministrator() || team.AuthorId != User.Id())
            {
                return Unauthorized();
            }


            await teamService.DeleteTeamAsync(id);

            TempData[GlobalMessageKey] = "Team was successfully deleted!";

            return RedirectToAction(nameof(All));
        }


        public async Task<IActionResult> Edit(int id)
        {
            var team = await teamService.GetByIdAsync<EditTeamFormModel>(id);

            team.MidLaners = await teamService.GetRoleAsync(Role.Mid);
            team.BottomLaners = await teamService.GetRoleAsync(Role.Bottom);
            team.SupportLaners = await teamService.GetRoleAsync(Role.Support);
            team.JungleLaners = await teamService.GetRoleAsync(Role.Jungle);
            team.TopLaners = await teamService.GetRoleAsync(Role.Top);

            if (team == null)
            {
                return NotFound();
            }

            if (!User.IsAdministrator() || team.AuthorId != User.Id())
            {
                return Unauthorized();
            }

            return View(team);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTeamFormModel input)
        {
            if (!ModelState.IsValid)
            {
                input.MidLaners = await teamService.GetRoleAsync(Role.Mid);
                input.BottomLaners = await teamService.GetRoleAsync(Role.Bottom);
                input.SupportLaners = await teamService.GetRoleAsync(Role.Support);
                input.JungleLaners = await teamService.GetRoleAsync(Role.Jungle);
                input.TopLaners = await teamService.GetRoleAsync(Role.Top);

                return View(input);
            }

            var isExisting = await teamService.IsExistingAsync(input.Title, input.Id);

            if (isExisting)
            {
                ModelState.AddModelError(nameof(input.Title), TeamExistingErrorMessage);

                input.MidLaners = await teamService.GetRoleAsync(Role.Mid);
                input.BottomLaners = await teamService.GetRoleAsync(Role.Bottom);
                input.SupportLaners = await teamService.GetRoleAsync(Role.Support);
                input.JungleLaners = await teamService.GetRoleAsync(Role.Jungle);
                input.TopLaners = await teamService.GetRoleAsync(Role.Top);

                return View(input);
            }

            var teamAuthorId = await teamService.GetTeamAuthorIdAsync(input.Id);

            if (teamAuthorId != User.Id() && User.IsAdministrator())
            {
                return Unauthorized();
            }

            await teamService.EditTeamAsync(
                input.Id,
                input.Title,
                input.ImageUrl,
                input.MidLaner,
                input.TopLaner,
                input.JungleLaner,
                input.BottomLaner,
                input.SupportLaner);

            TempData[GlobalMessageKey] = "Team was edited successfully!";

            return RedirectToAction(nameof(All));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var team = await teamService.GetByIdAsync<TeamDetailsViewModel>(id);

            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        public async Task<IActionResult> Battle() => View(new BattleTeamFormModel()
        {
            FirstTeam = await teamService.GetAllTeamsAsync<TeamServiceModel>(),
            SecondTeam = await teamService.GetAllTeamsAsync<TeamServiceModel>()
        });

        [HttpPost]
        public async Task<IActionResult> Battle(BattleTeamFormModel input)
        {
            if (input.FirstTeamName == input.SecondTeamName)
            {
                ModelState.AddModelError(nameof(input.FirstTeamName), SameTeamExistingErrorMessage);
                ModelState.AddModelError(nameof(input.SecondTeamName), SameTeamExistingErrorMessage);

                input.FirstTeam = await teamService.GetAllTeamsAsync<TeamServiceModel>();
                input.SecondTeam = await teamService.GetAllTeamsAsync<TeamServiceModel>();

                return View(input);
            }

            var isWon = teamService.GetWiningTeamAsync(input.FirstTeamName, input.SecondTeamName);

            TempData[GlobalMessageKey] = $"You {(isWon.GetAwaiter().GetResult() ? "won" : "lost")} the battle";

            return RedirectToAction(nameof(All));
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E-SportManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/selectize/dist/css/selectize.default.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_SportManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E-SportManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Create">Create Player</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Create">Create Team</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="All">Players</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="All">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Battle">Battle</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (TempData.ContainsKey(GlobalConstants.GlobalMessageKey))
        {
            <div class="alert alert-success text-center" role="alert">
                @TempData[GlobalConstants.GlobalMessageKey]

            </div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/selectize/dist/js/standalone/selectize.min.js" type="text/javascript" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_PaginationPartial.cshtml
@model PaginationViewModel

<nav>
    <ul class="pagination">
        <li>
            <a class="btn btn-primary
              @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
               asp-action="All"
               asp-route-page="@Model.PreviousPage">
                Previous
            </a>
        </li>

        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            var active = i == Model.CurrentPage ? "active" : string.Empty;
            <li class="active-pages">
                <a class="@active"
               asp-action="All"
               asp-route-page="@i">
                    @i
                </a>
            </li>
        }
        <li>
            <a class="btn btn-primary
               @(Model.CurrentPage == Model.TotalPages || Model.TotalPages==0 ?"disabled" : string.Empty)"
               asp-action="All"
               asp-route-page="@Model.NextPage">
                Next
            </a>
        </li>
    </ul>
</nav>